{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "7SXpaKwwGe5x"
      },
      "source": [
        "# TM10007 Assignment template"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "YNIBQZig6LPp"
      },
      "source": [
        "## Data loading and cleaning\n",
        "\n",
        "Below are functions to load the dataset of your choice. After that, it is all up to you to create and evaluate a classification method. Beware, there may be missing values in these datasets. Good luck!"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 397
        },
        "id": "-NE_fTbKGe5z",
        "outputId": "eec4b482-f998-4f1b-e736-3b9db9970032"
      },
      "outputs": [],
      "source": [
        "# import packages\n",
        "import os\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "from sklearn import metrics\n",
        "from sklearn.model_selection import train_test_split\n",
        "from sklearn.preprocessing import StandardScaler, LabelEncoder, QuantileTransformer\n",
        "from sklearn.impute import SimpleImputer\n",
        "from sklearn.feature_selection import VarianceThreshold\n",
        "\n",
        "# Classifiers\n",
        "from worclipo.load_data import load_data"
      ]
    },
    {
      "attachments": {},
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### functions"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# function to split the dataset into train and test\n",
        "def split_set(X,y,test_size):\n",
        "\n",
        "    if os.path.exists('./TEST_set.csv'):\n",
        "        split_action = print('TEST_set.csv already exists')\n",
        "    else:\n",
        "        split_action = print('TEST_set.csv does not exist, generating new test and training sets')\n",
        "        X_train_csv, X_test_csv, y_train_csv, y_test_csv = train_test_split(X, y, test_size=test_size, random_state=10)\n",
        "\n",
        "        TESTSET = X_test_csv.merge(y_test_csv, left_index=True, right_index=True)\n",
        "        TESTSET.to_csv('TEST_set.csv')\n",
        "\n",
        "        TRAINSET = X_train_csv.merge(y_train_csv, left_index=True, right_index=True)\n",
        "        TRAINSET.to_csv('TRAIN_set.csv')\n",
        "        return split_action\n",
        "    "
      ]
    },
    {
      "attachments": {},
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# setting up the data to be processed"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "data = load_data()\n",
        "print(f'The number of samples: {len(data.index)}')\n",
        "print(f'The number of columns: {len(data.columns)}')\n",
        "print(type(data))\n",
        "\n",
        "# change lipoma = 1 and liposarcoma = 0 and encode labels\n",
        "group_names = list(set(data.label))\n",
        "data.loc[data['label'] == 'lipoma', 'label'] = 1\n",
        "data.loc[data['label'] == 'liposarcoma', 'label'] = 0\n",
        "data['label'] = pd.cut(data['label'], bins = 2, labels=group_names)\n",
        "print(data['label'].unique())\n",
        "label_diag = LabelEncoder()\n",
        "data['label'] = label_diag.fit_transform(data['label'])\n",
        "\n",
        "# assign X to measurements and y to outcome (lipoma/sarcoma)\n",
        "X = data.drop('label', axis=1)\n",
        "y = data['label']\n",
        "test_size = 0.3"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# code that splits the data into test and validation sets if this is not done already\n",
        "split_set(X,y,test_size)"
      ]
    },
    {
      "attachments": {},
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## import the training set"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "TRAIN = pd.read_csv('TRAIN_set.csv', index_col=0)\n",
        "X_train = TRAIN.drop('label', axis=1)\n",
        "y_train = TRAIN['label']\n",
        "\n",
        "TRAIN['label'] = pd.cut(TRAIN['label'], bins = 2, labels=group_names)\n",
        "print(TRAIN['label'].unique())\n",
        "label_diag = LabelEncoder()\n",
        "TRAIN['label'] = label_diag.fit_transform(TRAIN['label'])\n",
        "\n",
        "# split into training and validation set\n",
        "X_train, X_valid, y_train, y_valid = train_test_split(X_train, y_train, test_size=0.3, random_state=10)\n",
        "\n",
        "from sklearn.pipeline import Pipeline\n",
        "\n",
        "print(f'Size before preprocess: ', X_train.shape)\n",
        "\n",
        "pipe_preprocess = Pipeline([\n",
        "    (\"check nan\", SimpleImputer(missing_values=np.nan, strategy='mean')),\n",
        "    (\"scale\", StandardScaler()),\n",
        "    (\"variance\", VarianceThreshold(threshold=0)),\n",
        "])\n",
        "\n",
        "X_train = pipe_preprocess.fit_transform(X_train)\n",
        "X_valid = pipe_preprocess.transform(X_valid)\n",
        "print(f'Size after preprocess: ', X_train.shape)"
      ]
    },
    {
      "attachments": {},
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# Classify"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 32,
      "metadata": {},
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "0.875\n",
            "Pipeline(steps=[('classifier',\n",
            "                 LogisticRegression(C=0.01, penalty=None, random_state=1))])\n",
            "{'classifier': LogisticRegression(C=0.01, penalty=None, random_state=1), 'classifier__C': 0.01, 'classifier__class_weight': None, 'classifier__penalty': None}\n",
            "Test Precision: 0.46153846153846156\n",
            "Test Recall: 0.6\n",
            "Test ROC AUC Score: 0.55\n"
          ]
        },
        {
          "name": "stderr",
          "output_type": "stream",
          "text": [
            "c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:378: FitFailedWarning: \n",
            "220 fits failed out of a total of 4000.\n",
            "The score on these train-test partitions for these parameters will be set to nan.\n",
            "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
            "\n",
            "Below are more details about the failures:\n",
            "--------------------------------------------------------------------------------\n",
            "36 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 406, in fit\n",
            "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 180, in fit\n",
            "    self._validate_params()\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\base.py\", line 570, in _validate_params\n",
            "    validate_parameter_constraints(\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 97, in validate_parameter_constraints\n",
            "    raise InvalidParameterError(\n",
            "sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVC must be a str among {'rbf', 'linear', 'precomputed', 'poly', 'sigmoid'} or a callable. Got 'polynomial' instead.\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "48 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 406, in fit\n",
            "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 180, in fit\n",
            "    self._validate_params()\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\base.py\", line 570, in _validate_params\n",
            "    validate_parameter_constraints(\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 97, in validate_parameter_constraints\n",
            "    raise InvalidParameterError(\n",
            "sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVC must be a str among {'precomputed', 'rbf', 'linear', 'sigmoid', 'poly'} or a callable. Got 'polynomial' instead.\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "32 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 406, in fit\n",
            "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 180, in fit\n",
            "    self._validate_params()\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\base.py\", line 570, in _validate_params\n",
            "    validate_parameter_constraints(\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 97, in validate_parameter_constraints\n",
            "    raise InvalidParameterError(\n",
            "sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVC must be a str among {'rbf', 'poly', 'sigmoid', 'precomputed', 'linear'} or a callable. Got 'polynomial' instead.\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "8 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 406, in fit\n",
            "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 180, in fit\n",
            "    self._validate_params()\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\base.py\", line 570, in _validate_params\n",
            "    validate_parameter_constraints(\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 97, in validate_parameter_constraints\n",
            "    raise InvalidParameterError(\n",
            "sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVC must be a str among {'precomputed', 'rbf', 'sigmoid', 'poly', 'linear'} or a callable. Got 'polynomial' instead.\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "16 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 406, in fit\n",
            "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 180, in fit\n",
            "    self._validate_params()\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\base.py\", line 570, in _validate_params\n",
            "    validate_parameter_constraints(\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 97, in validate_parameter_constraints\n",
            "    raise InvalidParameterError(\n",
            "sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVC must be a str among {'poly', 'sigmoid', 'linear', 'precomputed', 'rbf'} or a callable. Got 'polynomial' instead.\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "12 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 406, in fit\n",
            "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 180, in fit\n",
            "    self._validate_params()\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\base.py\", line 570, in _validate_params\n",
            "    validate_parameter_constraints(\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 97, in validate_parameter_constraints\n",
            "    raise InvalidParameterError(\n",
            "sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVC must be a str among {'rbf', 'precomputed', 'poly', 'sigmoid', 'linear'} or a callable. Got 'polynomial' instead.\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "8 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 406, in fit\n",
            "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 180, in fit\n",
            "    self._validate_params()\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\base.py\", line 570, in _validate_params\n",
            "    validate_parameter_constraints(\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 97, in validate_parameter_constraints\n",
            "    raise InvalidParameterError(\n",
            "sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVC must be a str among {'poly', 'rbf', 'sigmoid', 'linear', 'precomputed'} or a callable. Got 'polynomial' instead.\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "60 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 406, in fit\n",
            "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\naive_bayes.py\", line 774, in fit\n",
            "    self._count(X, Y)\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\naive_bayes.py\", line 896, in _count\n",
            "    check_non_negative(X, \"MultinomialNB (input X)\")\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 1408, in check_non_negative\n",
            "    raise ValueError(\"Negative values in data passed to %s\" % whom)\n",
            "ValueError: Negative values in data passed to MultinomialNB (input X)\n",
            "\n",
            "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
            "c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\model_selection\\_search.py:953: UserWarning: One or more of the test scores are non-finite: [0.65   0.65   0.6125 0.675  0.7    0.6375 0.6375 0.6375 0.65   0.7\n",
            " 0.6375 0.6375 0.6375 0.65   0.7    0.5    0.6    0.65   0.65   0.625\n",
            " 0.55   0.525  0.6375 0.65   0.625  0.55   0.525  0.6375 0.65   0.625\n",
            " 0.475  0.6    0.6    0.625  0.6    0.5375 0.5625 0.6125 0.625  0.575\n",
            " 0.5375 0.5625 0.6125 0.625  0.575  0.4625 0.625  0.6    0.625  0.6\n",
            " 0.5    0.575  0.6125 0.6125 0.6    0.5    0.5625 0.6125 0.6125 0.6\n",
            " 0.725  0.75      nan 0.65   0.725  0.825     nan 0.775  0.725  0.825\n",
            "    nan 0.75   0.725  0.825     nan 0.75   0.725  0.75      nan 0.775\n",
            " 0.725  0.75      nan 0.65   0.725  0.75      nan 0.6    0.725  0.75\n",
            "    nan 0.6    0.875  0.725  0.8    0.75   0.75   0.75   0.775  0.75\n",
            " 0.875  0.8    0.8    0.775  0.75   0.775  0.775  0.775  0.875  0.75\n",
            " 0.8    0.75   0.75   0.75   0.775  0.75   0.875  0.775  0.8    0.775\n",
            " 0.75   0.775  0.775  0.775  0.875  0.775  0.8    0.775  0.75   0.775\n",
            " 0.775  0.775  0.5    0.5125 0.525  0.5    0.5125 0.525  0.5    0.5125\n",
            " 0.525  0.5    0.5125 0.525  0.525  0.5125 0.5125 0.525  0.5125 0.5125\n",
            " 0.525  0.5125 0.5125 0.525  0.5125 0.5125 0.5125 0.5125 0.5125 0.5125\n",
            " 0.5125 0.5125 0.5125 0.5125 0.5125 0.5125 0.5125 0.5125 0.5375 0.5375\n",
            " 0.5375 0.525  0.525  0.525  0.525  0.525  0.525  0.525  0.525  0.525\n",
            " 0.6125 0.6875 0.6625 0.75   0.5       nan    nan    nan 0.4375 0.45\n",
            " 0.4125 0.5125 0.4375 0.45   0.4125 0.5125 0.4375 0.45   0.4125 0.5125]\n",
            "  warnings.warn(\n",
            "c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\linear_model\\_logistic.py:1181: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters\n",
            "  warnings.warn(\n"
          ]
        }
      ],
      "source": [
        "from sklearn.metrics import classification_report, confusion_matrix\n",
        "from sklearn.model_selection import GridSearchCV\n",
        "\n",
        "import pandas as pd\n",
        "from sklearn.linear_model import LogisticRegression\n",
        "from sklearn.svm import SVC\n",
        "from sklearn.ensemble import RandomForestClassifier\n",
        "from sklearn.ensemble import GradientBoostingClassifier\n",
        "from sklearn.pipeline import Pipeline\n",
        "from sklearn.model_selection import GridSearchCV, RandomizedSearchCV\n",
        "from sklearn.tree import DecisionTreeClassifier\n",
        "from sklearn.naive_bayes import MultinomialNB\n",
        "from sklearn.neighbors import KNeighborsClassifier\n",
        "from sklearn.metrics import *\n",
        "\n",
        "\n",
        "# setup classifiers\n",
        "clf1 = RandomForestClassifier(random_state=1)\n",
        "clf2 = SVC(probability=True, random_state=1)\n",
        "clf3 = LogisticRegression(random_state=1)\n",
        "clf4 = DecisionTreeClassifier(random_state=1)\n",
        "clf5 = KNeighborsClassifier()\n",
        "clf6 = MultinomialNB()\n",
        "clf7 = GradientBoostingClassifier(random_state=1)\n",
        "\n",
        "# Initiaze the hyperparameters for each dictionary\n",
        "param1 = {}\n",
        "param1['classifier__n_estimators'] = [1,10, 50, 100, 250]\n",
        "param1['classifier__max_depth'] = [5, 10, 20]\n",
        "param1['classifier__class_weight'] = [None, {0:1,1:5}, {0:1,1:10}, {0:1,1:25}]\n",
        "param1['classifier'] = [clf1]\n",
        "\n",
        "param2 = {}\n",
        "param2['classifier__C'] = [1,10]\n",
        "param2['classifier__class_weight'] = [None, {0:1,1:5}, {0:1,1:10}, {0:1,1:25}]\n",
        "param2['classifier__kernel'] = ['linear','rbf','polynomial','sigmoid']\n",
        "param2['classifier'] = [clf2]\n",
        "\n",
        "\n",
        "param3 = {}\n",
        "param3['classifier__C'] = [10**-2, 10**-1, 10**0, 10**1, 10**2]\n",
        "param3['classifier__penalty'] = [None, 'l2']\n",
        "param3['classifier__class_weight'] = [None, {0:1,1:5}, {0:1,1:6}, {0:1,1:7}]\n",
        "param3['classifier'] = [clf3]\n",
        "\n",
        "param4 = {}\n",
        "param4['classifier__max_depth'] = [5,10,25,None]\n",
        "param4['classifier__min_samples_split'] = [2,5,10]\n",
        "param4['classifier__class_weight'] = [{0:1,1:2}, {0:1,1:3}, {0:1,1:4}, {0:1,1:5}]\n",
        "param4['classifier'] = [clf4]\n",
        "\n",
        "param5 = {}\n",
        "param5['classifier__n_neighbors'] = [2,5,10,25,50]\n",
        "param5['classifier'] = [clf5]\n",
        "\n",
        "param6 = {}\n",
        "param6['classifier__alpha'] = [10**0, 10**1, 10**2]\n",
        "param6['classifier'] = [clf6]\n",
        "\n",
        "param7 = {}\n",
        "param7['classifier__n_estimators'] = [10, 50, 100, 250]\n",
        "param7['classifier__max_depth'] = [5, 10, 20]\n",
        "param7['classifier'] = [clf7]\n",
        "\n",
        "pipeline = Pipeline([('classifier', clf1)])\n",
        "params = [param1, param2, param3, param4, param5, param6, param7]\n",
        "\n",
        "gs = GridSearchCV(pipeline, params, cv=20, n_jobs=-1, scoring='roc_auc').fit(X_train, y_train)\n",
        "\n",
        "print(gs.best_score_)\n",
        "print(gs.best_estimator_)\n",
        "print(gs.best_params_)\n",
        "\n",
        "\n",
        "# Test data performance\n",
        "print(\"Test Precision:\",precision_score(gs.predict(X_valid), y_valid))\n",
        "print(\"Test Recall:\",recall_score(gs.predict(X_valid), y_valid))\n",
        "print(\"Test ROC AUC Score:\",roc_auc_score(gs.predict(X_valid), y_valid))\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 24,
      "metadata": {},
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0, 31.0, 32.0, 33.0, 34.0, 35.0, 36.0, 37.0, 38.0, 39.0, 40.0, 41.0, 42.0, 43.0, 44.0, 45.0, 46.0, 47.0, 48.0, 49.0, 50.0, 51.0, 52.0, 53.0, 54.0, 55.0, 56.0, 57.0, 58.0, 59.0, 60.0, 61.0, 62.0, 63.0, 64.0, 65.0, 66.0, 67.0, 68.0, 69.0, 70.0, 71.0, 72.0, 73.0, 74.0, 75.0, 76.0, 77.0, 78.0, 79.0, 80.0, 81.0, 82.0, 83.0, 84.0, 85.0, 86.0, 87.0, 88.0, 89.0, 90.0, 91.0, 92.0, 93.0, 94.0, 95.0, 96.0, 97.0, 98.0, 99.0, 100.0]\n"
          ]
        }
      ],
      "source": [
        "print([v for v in np.linspace(1,100,100)])"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 33,
      "metadata": {},
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "0.7866666666666666\n",
            "SVC(C=0.11009009009009008, kernel='linear', max_iter=1000, probability=True,\n",
            "    random_state=1)\n",
            "rfc               precision    recall  f1-score   support\n",
            "\n",
            "           0       0.50      0.64      0.56        11\n",
            "           1       0.60      0.46      0.52        13\n",
            "\n",
            "    accuracy                           0.54        24\n",
            "   macro avg       0.55      0.55      0.54        24\n",
            "weighted avg       0.55      0.54      0.54        24\n",
            "\n",
            "[[7 4]\n",
            " [7 6]]\n"
          ]
        },
        {
          "name": "stderr",
          "output_type": "stream",
          "text": [
            "c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:378: FitFailedWarning: \n",
            "10000 fits failed out of a total of 40000.\n",
            "The score on these train-test partitions for these parameters will be set to nan.\n",
            "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
            "\n",
            "Below are more details about the failures:\n",
            "--------------------------------------------------------------------------------\n",
            "771 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 180, in fit\n",
            "    self._validate_params()\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\base.py\", line 570, in _validate_params\n",
            "    validate_parameter_constraints(\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 97, in validate_parameter_constraints\n",
            "    raise InvalidParameterError(\n",
            "sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVC must be a str among {'poly', 'rbf', 'sigmoid', 'linear', 'precomputed'} or a callable. Got 'polynomial' instead.\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "817 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 180, in fit\n",
            "    self._validate_params()\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\base.py\", line 570, in _validate_params\n",
            "    validate_parameter_constraints(\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 97, in validate_parameter_constraints\n",
            "    raise InvalidParameterError(\n",
            "sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVC must be a str among {'precomputed', 'linear', 'poly', 'rbf', 'sigmoid'} or a callable. Got 'polynomial' instead.\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "855 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 180, in fit\n",
            "    self._validate_params()\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\base.py\", line 570, in _validate_params\n",
            "    validate_parameter_constraints(\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 97, in validate_parameter_constraints\n",
            "    raise InvalidParameterError(\n",
            "sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVC must be a str among {'linear', 'sigmoid', 'precomputed', 'rbf', 'poly'} or a callable. Got 'polynomial' instead.\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "850 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 180, in fit\n",
            "    self._validate_params()\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\base.py\", line 570, in _validate_params\n",
            "    validate_parameter_constraints(\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 97, in validate_parameter_constraints\n",
            "    raise InvalidParameterError(\n",
            "sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVC must be a str among {'linear', 'sigmoid', 'precomputed', 'poly', 'rbf'} or a callable. Got 'polynomial' instead.\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "835 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 180, in fit\n",
            "    self._validate_params()\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\base.py\", line 570, in _validate_params\n",
            "    validate_parameter_constraints(\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 97, in validate_parameter_constraints\n",
            "    raise InvalidParameterError(\n",
            "sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVC must be a str among {'rbf', 'poly', 'sigmoid', 'precomputed', 'linear'} or a callable. Got 'polynomial' instead.\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "834 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 180, in fit\n",
            "    self._validate_params()\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\base.py\", line 570, in _validate_params\n",
            "    validate_parameter_constraints(\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 97, in validate_parameter_constraints\n",
            "    raise InvalidParameterError(\n",
            "sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVC must be a str among {'rbf', 'linear', 'precomputed', 'poly', 'sigmoid'} or a callable. Got 'polynomial' instead.\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "823 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 180, in fit\n",
            "    self._validate_params()\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\base.py\", line 570, in _validate_params\n",
            "    validate_parameter_constraints(\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 97, in validate_parameter_constraints\n",
            "    raise InvalidParameterError(\n",
            "sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVC must be a str among {'poly', 'sigmoid', 'linear', 'precomputed', 'rbf'} or a callable. Got 'polynomial' instead.\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "834 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 180, in fit\n",
            "    self._validate_params()\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\base.py\", line 570, in _validate_params\n",
            "    validate_parameter_constraints(\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 97, in validate_parameter_constraints\n",
            "    raise InvalidParameterError(\n",
            "sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVC must be a str among {'precomputed', 'rbf', 'sigmoid', 'poly', 'linear'} or a callable. Got 'polynomial' instead.\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "854 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 180, in fit\n",
            "    self._validate_params()\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\base.py\", line 570, in _validate_params\n",
            "    validate_parameter_constraints(\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 97, in validate_parameter_constraints\n",
            "    raise InvalidParameterError(\n",
            "sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVC must be a str among {'rbf', 'poly', 'linear', 'precomputed', 'sigmoid'} or a callable. Got 'polynomial' instead.\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "830 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 180, in fit\n",
            "    self._validate_params()\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\base.py\", line 570, in _validate_params\n",
            "    validate_parameter_constraints(\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 97, in validate_parameter_constraints\n",
            "    raise InvalidParameterError(\n",
            "sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVC must be a str among {'rbf', 'precomputed', 'poly', 'sigmoid', 'linear'} or a callable. Got 'polynomial' instead.\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "855 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 180, in fit\n",
            "    self._validate_params()\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\base.py\", line 570, in _validate_params\n",
            "    validate_parameter_constraints(\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 97, in validate_parameter_constraints\n",
            "    raise InvalidParameterError(\n",
            "sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVC must be a str among {'precomputed', 'rbf', 'linear', 'sigmoid', 'poly'} or a callable. Got 'polynomial' instead.\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "842 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 180, in fit\n",
            "    self._validate_params()\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\base.py\", line 570, in _validate_params\n",
            "    validate_parameter_constraints(\n",
            "  File \"c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 97, in validate_parameter_constraints\n",
            "    raise InvalidParameterError(\n",
            "sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVC must be a str among {'sigmoid', 'precomputed', 'poly', 'linear', 'rbf'} or a callable. Got 'polynomial' instead.\n",
            "\n",
            "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
            "c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\model_selection\\_search.py:953: UserWarning: One or more of the test scores are non-finite: [0.77 0.54  nan ... 0.73  nan 0.69]\n",
            "  warnings.warn(\n",
            "c:\\ProgramData\\miniconda3\\lib\\site-packages\\sklearn\\linear_model\\_logistic.py:1181: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters\n",
            "  warnings.warn(\n"
          ]
        }
      ],
      "source": [
        "\n",
        "\n",
        "from sklearn.model_selection import GridSearchCV\n",
        "\n",
        "import pandas as pd\n",
        "from sklearn.linear_model import LogisticRegression\n",
        "from sklearn.svm import SVC\n",
        "from sklearn.ensemble import RandomForestClassifier\n",
        "from sklearn.ensemble import GradientBoostingClassifier\n",
        "from sklearn.pipeline import Pipeline\n",
        "from sklearn.model_selection import GridSearchCV, RandomizedSearchCV\n",
        "from sklearn.tree import DecisionTreeClassifier\n",
        "from sklearn.naive_bayes import MultinomialNB\n",
        "from sklearn.neighbors import KNeighborsClassifier\n",
        "from sklearn.metrics import *\n",
        "\n",
        "gsb = GridSearchCV(\n",
        "    estimator=SVC(probability=True,random_state=1,max_iter=1000),\n",
        "    param_grid={'kernel':['linear','rbf','polynomial','sigmoid'],'C':[v for v in np.linspace(0.01,100,1000)]},\n",
        "    cv = 10,\n",
        "    n_jobs=-1,\n",
        ").fit(X_train,y_train)\n",
        "\n",
        "print(gsb.best_score_)\n",
        "print(gsb.best_estimator_)\n",
        "\n",
        "best_clf = LogisticRegression(C=0.01, penalty=None, random_state=1)\n",
        "best_clf.fit(X_train,y_train)\n",
        "pred_rfc = best_clf.predict(X_valid)\n",
        "\n",
        "print('rfc', classification_report(y_valid, pred_rfc))\n",
        "print(confusion_matrix(y_valid, pred_rfc))\n",
        "\n",
        "\n",
        "results = pd.DataFrame(gsb.cv_results_)\n",
        "results = results.sort_values(by=['rank_test_score'])\n",
        "results.to_csv('results')\n"
      ]
    }
  ],
  "metadata": {
    "colab": {
      "name": "assignment.ipynb",
      "provenance": []
    },
    "kernelspec": {
      "display_name": "Python 3",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "codemirror_mode": {
        "name": "ipython",
        "version": 3
      },
      "file_extension": ".py",
      "mimetype": "text/x-python",
      "name": "python",
      "nbconvert_exporter": "python",
      "pygments_lexer": "ipython3",
      "version": "3.10.9"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}
